version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # This references the separate Dockerfile
    ports:
      - '3002:3001'
    restart: on-failure
    container_name: backend-container
     # Corrected volume syntax
